version: 2

models:
  - name: preppin
    columns:
      - name: online_or_in_person
        data_tests:
         - not_null
      - name: quarter
        data_tests:
         - not_null
      - name: value
        data_tests:
          - not_null        
      - name: quarterly_targets
        data_tests:
          - not_null 
      - name: variance
        data_tests:
          - not_null 
  - name: final_output
    description: final model for variance calculation through the join of 2 staging models.
    columns:
      - name: online_or_in_person
        data_tests:
         - not_null
      - name: quarter
        data_tests:
         - not_null
      - name: value
        data_tests:
          - not_null        
      - name: quarterly_targets
        data_tests:
          - not_null 
      - name: variance
        data_tests:
          - not_null 
  - name: quarterly_dsb_transactions
    description: staging model gotten from our raw transactions table filterd to DSB.
    columns:
      - name: online_or_in_person
        data_tests:
         - not_null
      - name: quarter
        data_tests:
         - not_null
      - name: value
        data_tests:
          - not_null 
  - name: quarterly_targets
    description: staging model gotten from our raw targets table.
    columns:
      - name: online_or_in_person
        data_tests:
         - not_null
      - name: quarter
        data_tests:
         - not_null
      - name: quarterly_targets
        data_tests:
          - not_null       
           